<<: !include ../hpack-defaults.yaml

name:               sentry
version:            0.0.0
build-type:         Simple

# common dependencies, shared between all targets
dependencies:
  # core libraries
  - base
  - async
  - bytestring
  - stm
  - text
  - time
  # hackage dependencies
  - aeson
  - hs-opentelemetry-instrumentation-http-client
  - http-client
  - patrol
  - sentry-core
  - unagi-chan
  - unliftio

library:
  source-dirs: library

tests:
  unit:
    source-dirs: tests/unit
    main: Driver.hs
    ghc-options:
      - -g
      - -Wno-missed-specialisations
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools: ["tasty-discover:tasty-discover"]
    dependencies:
      # library under test
      - sentry
      # test frameworks
      - hspec
      - tasty
      - tasty-discover
      - tasty-hspec

benchmarks:
  time:
    source-dirs: benchmarks
    main: Main.hs
    ghc-options:
      - -g
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-A32M -N"'
    dependencies:
      # library under test
      - sentry
      # test frameworks
      - tasty
      - tasty-bench
