<<: !include ../hpack-defaults.yaml

name:               sentry-optics
version:            0.0.0
build-type:         Simple
synopsis:           Optics-based authoring for Sentry scope updates, with the default HTTP transport.

dependencies:
  - base
  - sentry
  - sentry-core-optics

library:
  source-dirs: library

tests:
  unit:
    source-dirs: tests/unit
    main: Driver.hs
    ghc-options: -g -threaded -rtsopts -with-rtsopts=-N
    build-tools: ["tasty-discover:tasty-discover"]
    dependencies:
      - data-default
      - hspec
      - sentry-core
      - sentry-optics
      - tasty
      - tasty-discover
      - tasty-hspec >= 1.2
