<<: !include ../hpack-defaults.yaml

name:               sentry-core
version:            0.0.0
build-type:         Simple

# common dependencies, shared between all targets
dependencies:
  # core libraries
  - base
  - containers
  - deepseq
  - text
  - time
  - vector
  # hackage dependencies
  - atomic-primops
  - data-default
  - hs-opentelemetry-api
  - aeson
  - annotated-exception
  - exceptions
  - hs-opentelemetry-instrumentation-http-client
  - network-uri
  - patrol ^>= 1.2
  - random
  - safe-exceptions
  - mtl
  - transformers
  - unliftio-core
  - unordered-containers
  - network-bsd
  - witch

library:
  source-dirs: library

tests:
  unit:
    source-dirs: tests/unit
    main: Driver.hs
    ghc-options: -g -threaded -rtsopts -with-rtsopts=-N
    build-tools: ["tasty-discover:tasty-discover"]
    dependencies:
      - hspec
      - sentry-core
      - tasty
      - tasty-discover
      - tasty-hspec

benchmarks:
  time:
    source-dirs: benchmarks/time
    main: Main.hs
    ghc-options: -with-rtsopts=-A32m
    dependencies:
      - sentry-core
      - tasty
      - tasty-bench
  space:
    source-dirs: benchmarks/space
    main: Main.hs
    ghc-options: -with-rtsopts=-A32m
    dependencies:
      - sentry-core
      - weigh
