name: pinact

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pinact-check:
    runs-on: namespace-profile-mercury-oss-linux;overrides.cache-tag=sentry-haskell-pinact
    steps:
      - name: git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Mount Nix store cache
        uses: namespacelabs/nscloud-cache-action@c5f8dab7560444c4bf8dbc64f1b203431873c547 # v1.6.1
        with:
          cache: nix
      - name: Install Lix
        uses: ./.github/actions/install-lix
      - name: Run pinact check
        run: nix run .#pinact -- run --check --verify
